import { DataProvider } from '@/hooks/use-data';
import MainLayoutClient from './main-layout-client';
import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: 'Academic Tracker',
  description: 'Generated by Firebase Studio',
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
       <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=PT+Sans:wght@400;700&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        <DataProvider>
          <MainLayoutClient>{children}</MainLayoutClient>
        </DataProvider>
        <Toaster />
      </body>
    </html>
  );
}
